# Case study definition
# name of the case study. The problem formulation and ouptuts will be printed into the following relative path from main directory : case_studies/config['case_study']
'case_study': 'SA_FINAL_19-02-2025/2050'
#'case_study': 'Anne_CS_22_11/SA_26_11_24/2025'
'data_dir': 'Data/SA_FINAL_19-02-2025/2050' # Folders containing the csv data files

#'data_dir': 'Data/FEDECOM/CH_10'  # Folders containing the csv data files
'LCA_max' : 14000; #2015 : 115000 / #2020 : 91000 / 2025 : 72000 / 2030 : 56000 / 2035 : 42000  / 2040 : 29000 / 2045 : 20000 / 2050 : 14000
# number of typical days to consider
'nbr_td': 12
# Dictionnary with the dataframes containing all the data in the form : {'Demand': eud, 'Resources': resources, 'Technologies': technologies, 'End_uses_categories': end_uses_categories, 'Layers_in_out': layers_in_out, 'Storage_characteristics': storage_characteristics, 'Storage_eff_in': storage_eff_in, 'Storage_eff_out': storage_eff_out, 'Time_series': time_series, 'Misc': misc}
'all_data': {}

#Criteria limits
#CAUTION : The limits used for criteria normalization (defined in es_model.mod line 164) have to be modify to explore "extreme" scenarios
#REMARK : The weights of criteria can be change in es_model.mod line 159

##### MC parameters ####

'Cost_min': 1000;
'LCA_min' : 1000;
'Crit_1_min': 1;
'Crit_2_min': 1;
'Crit_3_min': 1;

'Cost_max': 200000;
'Crit_1_max': 10000000000;
'Crit_2_max': 10000000000;
'Crit_3_max': 10000000000;
'Weight_Cost' : 1.0; #COST
'Weight_LCA' : 0.0; #GWP
'Weight_Crit1' : 0.0; #ECO
'Weight_Crit2' : 0.0; #LU
'Weight_Crit3' : 0.0; #MD

'Weight_GWP' : 0;
'GWP_min': 0;
'GWP_max': 1000000000;

# Relative path from main directory to energyscope subdirectories and files

'es_path': 'energyscope/energy_model'  # Path to the energy model (.mod and .run files)
'cs_path': 'case_studies' # Path to the directory containing the different case studies
'step1_path': 'energyscope/preprocessing/td_selection' # Path to the step1 selection of typical days

# Printing input files for optimisation model
# printing the data in ETSD_data.dat file for the optimisation problem
printing: True
# printing the time related data in ESTD_12TD.dat for the optimisation problem
printing_td: True

# Run options for optimization problem
# path to AMPL licence directory (to adapt by the user), set to None if AMPL is in your PATH variables
# /!\ Don't use "\" but rather "\\" or "/"
'AMPL_path': 
# options for ampl -> (initialy barconvtol=1e-6)
'ampl_options' : {'show_stats': 3,
                  'log_file': 'output/log.txt',
                  'presolve': 10,
                  'presolve_eps': 1e-7,
                  'presolve_fixeps': 1e-7,
                  'show_boundtol': 0,
                  '_log_input_only': False,
                  'solver': 'gurobi',
                  'gurobi_options' : 'predual=-1 method=2 crossover=0 prepasses=3 barconvtol=1e-6 presolve=-1'
}
# Printing more detailed outputs
'print_barh' : False
'print_hourly_data': False
'print_sankey': True

#Post-process
'save_MC_outputs' : False
'LCA_postprocess': False
